version: "3.9"
services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c 'lib/wait redis:6379 -- npm run develop'
    depends_on:
      - redis
  redis:
    image: redis
volumes:
  node_modules: {}
