version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run develop
    depends_on:
      - redis
  redis:
    image: redis
volumes:
  node_modules: {}
